Teams: Make the action buttons to show icons only for mobile screens
open-learning-exchange/planet pull request #7173
Opened 2023-06-26 17:47 UTC by Mutugiii

- add the checkMobile service to the teams
- make teams action buttons to display icons in mobile screens 
- separate the styles from the component file to a separate style sheet(Past 12 lines as in style-guide.md)

Fixes #7169

2023-06-29 18:42 UTC, Mutugiii commented
On hold for #7166

2023-07-11 17:18 UTC, lmmrssa requested changes

2023-07-11 17:18 UTC, lmmrssa commented on src/app/teams/teams.component.html
> +                <mat-icon>feedback</mat-icon> Feedback
only label can be part of if condition

2023-07-11 17:18 UTC, lmmrssa commented on src/app/teams/teams.component.html
> +                  <mat-icon>add_circle</mat-icon> Request to Join
label only in condition

2023-07-11 17:18 UTC, lmmrssa commented on src/app/teams/teams.component.html
> +                  <mat-icon>hourglass_empty</mat-icon> Request pending
label only in condition

2023-07-11 17:18 UTC, lmmrssa commented on src/app/teams/teams.component.html
> +                <mat-icon>delete_forever</mat-icon> Delete
label only in condition

2023-07-18 17:38 UTC, lmmrssa approved these changes

2023-07-19 16:36 UTC, merged