show details: Placed Card at Top of Page (fixes #7641)
open-learning-exchange/planet pull request #7650
Opened 2024-10-25 13:53 UTC by sahilvunnam

Fixes #7641 

![Image 10-25-24 at 6 10 AM](https://github.com/user-attachments/assets/7f4c923a-65db-4260-aa46-bdbc6c35b630)

2024-10-25 16:02 UTC, jessewashburn approved these changes

2024-10-25 16:04 UTC, jessewashburn requested changes
This fix works, but I think your editor added some spaces to 2 file, which were not necessary to change.

2024-10-25 16:31 UTC, RheuX approved these changes

2024-10-25 19:42 UTC, Gavinp14 approved these changes

2024-10-25 20:15 UTC, Mutugiii approved these changes

2024-10-25 20:26 UTC, Mutugiii commented
The additional spaces being added is the expected behaviour given our pre-push linting hooks, and they help with our code analyser i.e
- https://codeclimate.com/github/open-learning-exchange/planet/src/app/manager-dashboard/reports/reports.component.ts 
- https://codeclimate.com/github/open-learning-exchange/planet/src/app/surveys/surveys.component.ts


Looks like the 2 spaces were not noticed in the last week pushes.

Be sure to run: `npm run install-hooks` as it catches these simple spacing issues.

cc: @jessewashburn @RheuX

2024-10-25 20:29 UTC, jessewashburn approved these changes

2024-10-28 19:39 UTC, dogi approved these changes

2024-10-28 19:40 UTC, merged