Courses/Library: dynamic label for adding and editing resources (Fixes #7728)
open-learning-exchange/planet pull request #7731
Opened 2024-11-06 15:39 UTC by jessewashburn

Courses/resources now have a dynamic label based on the action (Add or Edit). 

Fixes #7728 

![image](https://github.com/user-attachments/assets/8eb65233-9b88-4ffa-8cf7-00860db62ca7)

![image](https://github.com/user-attachments/assets/341dc989-8c11-4d51-b9d1-57420a97c970)

![image](https://github.com/user-attachments/assets/11e06239-4292-4523-a447-358a48f0a634)

![image](https://github.com/user-attachments/assets/19de9358-5379-46e1-b9a4-698dd9b23d63)

2024-11-06 16:28 UTC, sahilvunnam approved these changes

2024-11-06 17:23 UTC, Gavinp14 approved these changes

2024-11-08 20:51 UTC, Mutugiii requested changes
In some parts of the code we find checks for pageType === 'Add New' or pageType === 'update'

e,g courses-add.component.ts line 202 & 234

2024-11-15 20:52 UTC, dogi approved these changes

2024-11-15 20:54 UTC, merged