reports: fixed title (fixes #6917)
open-learning-exchange/planet pull request #7743
Opened 2024-11-07 16:03 UTC by sahilvunnam

fixes #6917 

![Image 11-7-24 at 7 40 AM](https://github.com/user-attachments/assets/0f650c69-8b5d-4103-ab02-d95c1fcefac7)

2024-11-07 17:14 UTC, jessewashburn requested changes
The title should be dynamic, depending on whether the action is Add or Edit. Currently, it just says Edit, even if you're adding a new report. See my PR #7731 to see how I did this on other pages.

2024-11-08 14:50 UTC, sahilvunnam commented
@jessewashburn Just added dynamic title, please let me know if it works. Thank you

2024-11-08 16:19 UTC, Gavinp14 approved these changes

2024-11-08 20:57 UTC, RheuX approved these changes

2025-01-10 20:10 UTC, Mutugiii approved these changes

2025-01-10 20:53 UTC, merged