survey: smoother view (fixes #6561)
open-learning-exchange/planet pull request #7744
Opened 2024-11-07 16:52 UTC by sahilvunnam

fixes #6561

2024-11-07 17:18 UTC, jessewashburn approved these changes

2024-11-07 17:45 UTC, RheuX approved these changes

2024-11-08 16:18 UTC, Gavinp14 approved these changes

2024-11-08 20:48 UTC, Mutugiii requested changes
Surveys can be retaken to change answers, which can lead to issues like below i.e Being told to `finish survey` and submit answer not auto-redirecting to the next question

![image](https://github.com/user-attachments/assets/7e978696-8142-4121-a71e-93d1264a921a)

2024-12-02 11:18 UTC, closed without merging