resources: smoother collections display (fixes #7772)
open-learning-exchange/planet pull request #7776
Opened 2024-11-14 15:25 UTC by sahilvunnam

fixes #7772

2024-11-14 16:30 UTC, jessewashburn approved these changes

2024-11-14 19:13 UTC, RheuX approved these changes

2024-11-14 20:53 UTC, Gavinp14 approved these changes

2024-11-15 16:27 UTC, Mutugiii requested changes
This is only supported in the creation form, however you can edit the name and bypass the limit

![image](https://github.com/user-attachments/assets/19833790-bf15-409d-899d-dd4c3f63688d)

2024-12-11 21:34 UTC, Mutugiii approved these changes

2024-12-12 16:05 UTC, jessewashburn approved these changes

2024-12-13 21:21 UTC, dogi approved these changes

2024-12-13 21:23 UTC, merged