collections: smoother tag (fixes #5776)
open-learning-exchange/planet pull request #7778
Opened 2024-11-14 17:52 UTC by RheuX

Fixes #5776 

After deleting a tag, it the tag is available, it would not say value already exist, you can instantly add it to the collection.

If you delete `b` but trying to insert `a` while `a` is still exist, it will not let you do it

2024-11-14 18:41 UTC, jessewashburn approved these changes

2024-11-14 20:54 UTC, Gavinp14 approved these changes

2024-11-15 17:17 UTC, Mutugiii requested changes
This implementation allows me to add blank names(when I clear the textbox)

![image](https://github.com/user-attachments/assets/2ab896a2-5fea-42d8-bd69-cea913868314)

2024-11-19 19:32 UTC, dogi approved these changes

2024-11-19 19:34 UTC, merged