centered file upload items on small screens (fixes #7798)
open-learning-exchange/planet pull request #7801
Opened 2024-11-19 18:07 UTC by Gavinp14

<img width="348" alt="fileoverflowfix" src="https://github.com/user-attachments/assets/3d9f1b13-706c-4150-849f-e761af1118bf">

fixes #7798

2024-11-20 19:56 UTC, Mutugiii requested changes
If the filename is long or the screen size is small, the Choose File button may be pushed out of the visible screen area.

2024-11-21 13:50 UTC, Gavinp14 commented
@Mutugiii the button will no longer be moved off the screen if the filename is too long

2024-12-04 13:22 UTC, jessewashburn approved these changes

2024-12-23 12:49 UTC, Mutugiii approved these changes

2024-12-27 18:07 UTC, dogi approved these changes

2024-12-27 18:10 UTC, merged