added max length to step title (fixes #7867)
open-learning-exchange/planet pull request #7873
Opened 2024-12-02 17:51 UTC by Gavinp14

fixes #7867
Added a max length for creating a step title at 150 characters. If we feel like this is too short or too long, I can always make adjustments.  I don't think that there will be an actual need to create titles over 150 chars for steps.

2024-12-02 17:57 UTC, RheuX requested changes
I think this would work on larger screen,

for smaller screen it would still look like this.

![image](https://github.com/user-attachments/assets/9132b222-9f7b-4249-9107-a9696ee69418)

I figured we should probably truncate or anything based on screen sizes

2024-12-03 21:09 UTC, Gavinp14 commented
<img width="360" alt="smallscreenstepsfix" src="https://github.com/user-attachments/assets/3f6a5f85-4a36-474f-af0d-0b8979dad055">
It will now be responsive for smaller screens. Ellipses will also be added on all sized screens if step title exceeds a certain length.

2024-12-03 21:35 UTC, RheuX approved these changes

2024-12-04 13:07 UTC, jessewashburn approved these changes

2024-12-04 20:27 UTC, Mutugiii approved these changes

2024-12-04 20:52 UTC, dogi approved these changes

2024-12-04 21:02 UTC, merged