New Crowdin updates
open-learning-exchange/planet pull request #7895
Opened 2024-12-05 17:45 UTC by Mutugiii

2024-12-05 17:48 UTC, jessewashburn approved these changes

2024-12-09 14:55 UTC, jessewashburn requested changes
The following were not translated/updated: 

![image](https://github.com/user-attachments/assets/4dd164fc-d873-49e2-81ac-e0904871eb2b)

2025-07-09 21:38 UTC, Mutugiii commented
`Run sync` translation & icons not visible in the spanish translation

![image](https://github.com/user-attachments/assets/e3e6d1e4-cb19-459d-867d-1c9f84130a04)

2025-07-11 11:49 UTC, Mutugiii commented
Send icon as well

<img width="3406" height="1836" alt="image" src="https://github.com/user-attachments/assets/e82d6d84-8b14-4923-996b-ffda5c4881b3" />

2025-07-11 12:05 UTC, Mutugiii commented on src/app/dashboard/dashboard.component.ts
> +      { baseFirstLine: $localize` my `, title: $localize`Health`, link: 'myHealth' }
Not sure I understand the need for the spaces around `my`, similar to the myChat

2025-07-11 15:12 UTC, Mutugiii commented
Noticed:

- miTablero is `Panel de Control` in mobile sidebar
- Manager Settings & Logout not translated

<img width="2394" height="1850" alt="image" src="https://github.com/user-attachments/assets/9e27dfbe-7823-46e0-98d9-e1fe134b943d" />

2025-07-11 19:03 UTC, Mutugiii commented
Noticed that the `Courses Loading` and `Resources Loading` don't get translated

<img width="2388" height="1816" alt="image" src="https://github.com/user-attachments/assets/07abe4e1-b506-40f1-be14-91c24468c289" />

Similarly `No Course/Resource Found` is also not getting translated

<img width="3406" height="1838" alt="image" src="https://github.com/user-attachments/assets/7fc4bae5-de95-41aa-9478-20f4379442a3" />

2025-07-14 14:46 UTC, jessewashburn commented on src/app/dashboard/dashboard.component.ts
> +      { baseFirstLine: $localize` my `, title: $localize`Health`, link: 'myHealth' }
It's because we need 2 different versions of "my" (singular and plural). Adding spaces was the only way I could figure out to target those specific "my" strings to make them singular.

2025-07-14 14:52 UTC, Mutugiii commented on src/app/dashboard/dashboard.component.ts
> +      { baseFirstLine: $localize` my `, title: $localize`Health`, link: 'myHealth' }
Got it, thanks!

2025-07-14 20:52 UTC, PlataformasInformaticas approved these changes

2025-07-15 15:24 UTC, dogi approved these changes

2025-07-15 15:33 UTC, merged