resources: smoother collections (fixes #7928)
open-learning-exchange/planet pull request #7932
Opened 2024-12-12 19:25 UTC by RheuX

Fixes #7928 

![image](https://github.com/user-attachments/assets/300040a0-53c1-457f-8f0a-0634a6dd8e9d)

![image](https://github.com/user-attachments/assets/683990a9-f12c-432c-80b3-fb95279a76e0)

2024-12-13 15:22 UTC, Gavinp14 requested changes
For me, it is still overflowing on mobile or $screen-sm. Desktop looks good.
<img width="414" alt="axelissue" src="https://github.com/user-attachments/assets/27437666-3db5-44c6-bc58-635fd8162b59" />

2024-12-16 17:09 UTC, Gavinp14 approved these changes

2024-12-16 18:53 UTC, jessewashburn commented
lgtm. Still overflows in this window, but that could be a separate issue 
![image](https://github.com/user-attachments/assets/f9910926-029b-46db-a2c8-80a817d17379)

2024-12-17 21:29 UTC, dogi approved these changes

2024-12-17 21:31 UTC, merged