courses: smoother snackbar (fixes #7941)
open-learning-exchange/planet pull request #7953
Opened 2024-12-17 18:18 UTC by Gavinp14

fixes #7941

This is universal so it will truncate other snackbars if needed.

2024-12-17 18:25 UTC, jessewashburn approved these changes

2024-12-17 18:34 UTC, jessewashburn requested changes
Unfortunately, this will truncate not just the title, but the information following it. E.G if you join a course, you would want it to say "aaaaaaaaa.... added to your dashboard" not just "aaaaaaaaaaa..."  The universal approach may not work after all. 

![image](https://github.com/user-attachments/assets/c2742fd0-4013-4e75-81fd-cef6e39ee615)

2024-12-17 18:45 UTC, Gavinp14 commented
I see I will make this change just for the courses snack bar instead

2024-12-17 21:27 UTC, RheuX reviewed
is it supposed to like this? or is it supposed to be truncated?

![image](https://github.com/user-attachments/assets/f622f103-0a43-4b9e-8074-c8ba71a1e778)

![image](https://github.com/user-attachments/assets/bdd3aec5-56d8-4087-aac8-cd4056d16165)

2024-12-17 21:34 UTC, Gavinp14 commented
hmmm, it does not do this for my screen. @Mutugiii could you check this pr out on your side to see if anything is wrong?

2024-12-18 15:41 UTC, jessewashburn commented
> is it supposed to like this? or is it supposed to be truncated?

It's because the change for this PR is only related to the course deletion snackbar. For adding/removing courses to/from myLibrary, that's related to the courses.service.ts, similar to PR #7956

2024-12-18 15:41 UTC, jessewashburn approved these changes

2024-12-20 19:25 UTC, Mutugiii commented
@Gavinp14 Getting a similar issue to that of @RheuX

2025-01-14 16:22 UTC, jessewashburn commented
Fixed by #8088

2025-01-17 19:37 UTC, closed without merging