smoother member role title (fixes #7966)
open-learning-exchange/planet pull request #7970
Opened 2024-12-19 19:15 UTC by Gavinp14

fixes #7966

2024-12-19 19:27 UTC, jessewashburn requested changes
If you scroll down, there is still overflow. 
![image](https://github.com/user-attachments/assets/b7197a17-0e92-4d6d-87ec-fe2cac315701)

2024-12-19 19:49 UTC, Gavinp14 commented
@jessewashburn I decided to remove word break and just make it fixed on one line, I realized you need to leave room for the tasks user is assigned to. Let me know if it is still overflowing.

2024-12-20 15:36 UTC, jessewashburn requested changes
I think it should allow for slightly longer titles since there is plenty of space
![image](https://github.com/user-attachments/assets/884a09ef-490d-475e-951c-9bef58b8e9e4)

2024-12-20 17:17 UTC, Gavinp14 commented
@jessewashburn I agree there is plenty of room, however when a member is assigned more than two tasks, a member title that is more than two lines will cause overflow for the tasks as pictured below. I guess maybe this could be a separate issue in regard to the tasks list maybe. 
<img width="342" alt="jesseResponse" src="https://github.com/user-attachments/assets/03c93feb-6012-488a-a243-7dc67f4cd577" />

2024-12-20 17:56 UTC, jessewashburn commented
> @jessewashburn I agree there is plenty of room, however when a member is assigned more than two tasks, a member title that is more than two lines will cause overflow for the tasks as pictured below. I guess maybe this could be a separate issue in regard to the tasks list maybe. Could you please try to replicate this? 

I see. Yes, that does happen, but it can also happen when there is a long name. 
![image](https://github.com/user-attachments/assets/5f62b656-782f-4314-888a-b804559602b3)
Rather than catering to the task overflow issue, I would set up the title truncation assuming that tasks will not over flow and then fix the tasks issue separately.

2024-12-20 18:21 UTC, Gavinp14 commented
I will take a look and see what I can do, I might have to adjust some stuff in the task's component.

2024-12-27 19:33 UTC, jessewashburn requested changes
![image](https://github.com/user-attachments/assets/b60ebdf1-c226-4b87-bf39-5cc57f67ddba)

I think you still need to add word break. Not sure if you intended to fix the tasks overflow here, but this is what it looks like for me.

2025-02-14 21:31 UTC, jessewashburn commented
Fixed by PR #8240. Recommend closing

2025-02-17 21:39 UTC, closed without merging