change-collections: smoother buttons (fixes #7986)
open-learning-exchange/planet pull request #7989
Opened 2024-12-20 19:29 UTC by jessewashburn

fixes #7986

![image](https://github.com/user-attachments/assets/c01b5b02-f774-4a89-8667-736fb22944ae)

2024-12-23 21:06 UTC, Gavinp14 requested changes
This looks good, the only minor change would be to just move any overflowing names a bit to the left more so the parenthesis isn't cramped close to the edit button 
<img width="360" alt="tinyoverflowissue" src="https://github.com/user-attachments/assets/dd59833b-3262-4b55-84d2-426dadef970d" />

2024-12-24 15:50 UTC, jessewashburn commented
> This looks good, the only minor change would be to just move any overflowing names a bit to the left more so the parenthesis isn't cramped close to the edit button <img alt="tinyoverflowissue" width="360" src="https://private-user-images.githubusercontent.com/112116086/398257283-dd59833b-3262-4b55-84d2-426dadef970d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNTU3MDgsIm5iZiI6MTczNTA1NTQwOCwicGF0aCI6Ii8xMTIxMTYwODYvMzk4MjU3MjgzLWRkNTk4MzNiLTMyNjItNGI1NS04NGQyLTQyNmRhZGVmOTcwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQxNTUwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWU0OTNhMWIyNzY1ODJjNDgyYjZjNzkyNmZkMTVmYWNkNzg3ZWFmZmI5NDMyY2M3OGFhMDczZWRlMTI5MWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zq9Ot6ExdPKuRkqii-YFX-5cHFM4zAaCAOko7UTAd1M">

Good catch. Please re-review.

2025-01-13 20:09 UTC, RheuX approved these changes

2025-01-16 20:55 UTC, dogi approved these changes

2025-01-16 21:09 UTC, dogi approved these changes

2025-01-16 21:11 UTC, merged